In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
#movies = # Write your code for importing the csv file here
movies = pd.read_csv("Movie+Assignment+Data.csv")
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
movies.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
movies.isnull().sum(axis = 0)

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [7]:
# Write your code for column-wise null percentages here
round(100*(movies.isnull().sum()/len(movies.index)),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [8]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
df=movies.copy()
df=df.drop(["color","director_facebook_likes","actor_1_facebook_likes","actor_2_facebook_likes","actor_3_facebook_likes","actor_2_name","cast_total_facebook_likes","actor_3_name","duration","facenumber_in_poster","content_rating","country","movie_imdb_link","aspect_ratio","plot_keywords"],axis=1)
df.columns
round(100*(df.isnull().sum()/len(movies.index)),2)

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.24
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [9]:
# Write your code for dropping the rows here
df2= df.loc[:,round(100*df.isnull().sum()/len(df.index),2)>5]
df1=df.copy()
l=list(df2.columns)
for i in l:
    print(i)
    df1 = df1.loc[~df1[i].isnull(),]
    print(df1.shape)
df1.shape
#4159+884 = 5043 -- (y)

gross
(4159, 13)
budget
(3891, 13)

(3891, 13)

In [10]:
df1.shape
round(100*df1.isnull().sum()/len(df1.index),2)
#df1.isnull().sum(axis=1)>5
#df4=df1.loc[df1.isnull().sum(axis=1)>0,:]
#df4
df1.loc[df1.isnull().sum(axis=1) < 5]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
6,Sam Raimi,392.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258000000.0,2007.0,6.2,0
7,Nathan Greno,324.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260000000.0,2010.0,7.8,29000
8,Joss Whedon,635.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250000000.0,2015.0,7.5,118000
9,David Yates,375.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250000000.0,2009.0,7.5,10000
10,Zack Snyder,673.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250000000.0,2016.0,6.9,197000
11,Bryan Singer,434.0,200069408.0,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209000000.0,2006.0,6.1,0
12,Marc Forster,403.0,168368427.0,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200000000.0,2008.0,6.7,0
13,Gore Verbinski,313.0,423032628.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225000000.0,2006.0,7.3,5000
14,Gore Verbinski,450.0,89289910.0,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215000000.0,2013.0,6.5,48000
15,Zack Snyder,733.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225000000.0,2013.0,7.2,118000
16,Andrew Adamson,258.0,141614023.0,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225000000.0,2008.0,6.6,0
17,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000
18,Rob Marshall,448.0,241063875.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250000000.0,2011.0,6.7,58000
19,Barry Sonnenfeld,451.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225000000.0,2012.0,6.8,40000
20,Peter Jackson,422.0,255108370.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250000000.0,2014.0,7.5,65000
21,Marc Webb,599.0,262030663.0,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230000000.0,2012.0,7.0,56000
22,Ridley Scott,343.0,105219735.0,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200000000.0,2010.0,6.7,17000
23,Peter Jackson,509.0,258355354.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225000000.0,2013.0,7.9,83000
24,Chris Weitz,251.0,70083519.0,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180000000.0,2007.0,6.1,0
25,Peter Jackson,446.0,218051260.0,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207000000.0,2005.0,7.2,0
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000
27,Anthony Russo,516.0,407197282.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250000000.0,2016.0,8.2,72000
28,Peter Berg,377.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209000000.0,2012.0,5.9,44000
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000
30,Sam Mendes,750.0,304360277.0,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,1498.0,English,200000000.0,2012.0,7.8,80000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959,Robert Townsend,21.0,5228617.0,Comedy,Robert Townsend,Hollywood Shuffle,2770,32.0,English,100000.0,1987.0,7.0,471
4962,Larry Blamire,88.0,110536.0,Comedy|Horror|Sci-Fi,Fay Masterson,The Lost Skeleton of Cadavra,4117,118.0,English,40000.0,2001.0,7.0,0
4964,E.L. Katz,193.0,59379.0,Comedy|Crime|Drama|Horror|Thriller,Brighton Sharbino,Cheap Thrills,12796,52.0,English,200000.0,2013.0,6.8,0
4971,Dennis Iliadis,241.0,32721635.0,Crime|Horror|Thriller,Tony Goldwyn,The Last House on the Left,67824,279.0,English,15000000.0,2009.0,6.6,0
4973,Darren Aronofsky,138.0,3216970.0,Drama|Mystery|Thriller,Mark Margolis,Pi,142619,586.0,English,60000.0,1998.0,7.5,24000
4975,Myles Berkowitz,32.0,536767.0,Biography|Comedy|Romance,Tia Carrere,20 Dates,1622,83.0,English,60000.0,1998.0,5.3,30
4977,Morgan Spurlock,193.0,11529368.0,Comedy|Documentary|Drama,Chemeeka Walker,Super Size Me,85028,404.0,English,65000.0,2004.0,7.3,0
4978,Brandon Trost,66.0,40557.0,Comedy,Clifton Collins Jr.,The FP,1389,22.0,English,60000.0,2011.0,5.6,0
4979,Joe Swanberg,65.0,30084.0,Comedy|Drama,Anna Kendrick,Happy Christmas,5507,23.0,English,70000.0,2014.0,5.6,812
4984,Edward Burns,36.0,10246600.0,Comedy|Drama|Romance,Shari Albert,The Brothers McMullen,6375,36.0,English,25000.0,1995.0,6.6,265
4987,Lena Dunham,113.0,389804.0,Comedy|Drama|Romance,Lena Dunham,Tiny Furniture,11816,35.0,English,65000.0,2010.0,6.3,0
4997,David Gordon Green,75.0,241816.0,Drama,Paul Schneider,George Washington,6246,76.0,English,42000.0,2000.0,7.5,451
4998,Kevin Jordan,21.0,277233.0,Comedy|Romance,Derick Martini,Smiling Fish & Goat on Fire,2631,26.0,English,40000.0,1999.0,7.6,0
5004,Mike Bruce,3.0,243768.0,Western,Joseph Campanella,The Legend of God's Gun,143,9.0,English,30000.0,2007.0,4.1,13
5008,Kevin Smith,136.0,3151130.0,Comedy,Jason Mewes,Clerks,181749,615.0,English,230000.0,1994.0,7.8,0
5009,James Bidgood,8.0,8231.0,Drama|Fantasy,Don Brooks,Pink Narcissus,803,16.0,English,27000.0,1971.0,6.7,85
5011,Neil LaBute,80.0,2856622.0,Comedy|Drama,Stacy Edwards,In the Company of Men,11550,197.0,English,25000.0,1997.0,7.3,489
5012,David Ayer,233.0,10499968.0,Action|Crime|Drama|Thriller,Mireille Enos,Sabotage,47502,212.0,English,35000000.0,2014.0,5.7,10000
5015,Richard Linklater,61.0,1227508.0,Comedy|Drama,Tommy Pallotta,Slacker,15103,80.0,English,23000.0,1991.0,7.1,2000
5021,Jay Duplass,51.0,192467.0,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,71.0,English,15000.0,2005.0,6.6,297
5023,Daryl Wein,22.0,76382.0,Romance,Zoe Lister-Jones,Breaking Upwards,1194,8.0,English,15000.0,2009.0,6.2,324
5025,John Waters,73.0,180483.0,Comedy|Crime|Horror,Divine,Pink Flamingos,16792,183.0,English,10000.0,1972.0,6.1,0
5026,Olivier Assayas,81.0,136007.0,Drama|Music|Romance,Maggie Cheung,Clean,3924,39.0,French,4500.0,2004.0,6.9,171
5027,Jafar Panahi,64.0,673780.0,Drama,Fereshteh Sadre Orafaiy,The Circle,4555,26.0,Persian,10000.0,2000.0,7.5,697
5029,Kiyoshi Kurosawa,78.0,94596.0,Crime|Horror|Mystery|Thriller,KÃ´ji Yakusho,The Cure,6318,50.0,Japanese,1000000.0,1997.0,7.4,817
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry BishÃ©,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [11]:
# Write your code for dropping the rows here
df3=df1[df1.isnull().sum(axis=1) < 5]
    #df2= df.loc[:,round(100*df.isnull().sum()/len(df.index),2)>5]
df3.shape

(3891, 13)

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [12]:
# Write your code for filling the NaN values in the 'language' column here
df4=df3.loc[df3.isnull().sum(axis=1)>0,:]
col=df.loc[:,df3.isnull().sum()>0]
col
df5=df3.copy()
df5.loc[df5.language.isnull(),["language"]]='English'

In [13]:
df5.isnull().sum()

director_name             0
num_critic_for_reviews    1
gross                     0
genres                    0
actor_1_name              3
movie_title               0
num_voted_users           0
num_user_for_reviews      0
language                  0
budget                    0
title_year                0
imdb_score                0
movie_facebook_likes      0
dtype: int64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [14]:
# Write your code for checking number of retained rows here
df5.shape
100*(df.shape[0]-df5.shape[0])/df.shape[0]

22.84354550862582

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [15]:
# Write your code for unit conversion here
df5.loc[:,["budget","gross"]]=df5.loc[:,["budget","gross"]]//1000000
df5.loc[:,["budget","gross"]]

      budget  gross
0      237.0  760.0
1      300.0  309.0
2      245.0  200.0
3      250.0  448.0
5      263.0   73.0
6      258.0  336.0
7      260.0  200.0
8      250.0  458.0
9      250.0  301.0
10     250.0  330.0
11     209.0  200.0
12     200.0  168.0
13     225.0  423.0
14     215.0   89.0
15     225.0  291.0
16     225.0  141.0
17     220.0  623.0
18     250.0  241.0
19     225.0  179.0
20     250.0  255.0
21     230.0  262.0
22     200.0  105.0
23     225.0  258.0
24     180.0   70.0
25     207.0  218.0
26     200.0  658.0
27     250.0  407.0
28     209.0   65.0
29     150.0  652.0
30     200.0  304.0
...      ...    ...
4959     0.0    5.0
4962     0.0    0.0
4964     0.0    0.0
4971    15.0   32.0
4973     0.0    3.0
4975     0.0    0.0
4977     0.0   11.0
4978     0.0    0.0
4979     0.0    0.0
4984     0.0   10.0
4987     0.0    0.0
4997     0.0    0.0
4998     0.0    0.0
5004     0.0    0.0
5008     0.0    3.0
5009     0.0    0.0
5011     0.0    2.0
5012    35.0   10.0
5015     0.0    1.0
5021     0.0    0.0
5023     0.0    0.0
5025     0.0    0.0
5026     0.0    0.0
5027     0.0    0.0
5029     1.0    0.0
5033     0.0    0.0
5034     0.0    0.0
5035     0.0    2.0
5037     0.0    0.0
5042     0.0    0.0

[3891 rows x 2 columns]

In [16]:
df5

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0
2,Sam Mendes,602.0,200.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.0,2012.0,6.6,24000
6,Sam Raimi,392.0,336.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258.0,2007.0,6.2,0
7,Nathan Greno,324.0,200.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260.0,2010.0,7.8,29000
8,Joss Whedon,635.0,458.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250.0,2015.0,7.5,118000
9,David Yates,375.0,301.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250.0,2009.0,7.5,10000
10,Zack Snyder,673.0,330.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250.0,2016.0,6.9,197000
11,Bryan Singer,434.0,200.0,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209.0,2006.0,6.1,0
12,Marc Forster,403.0,168.0,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200.0,2008.0,6.7,0
13,Gore Verbinski,313.0,423.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225.0,2006.0,7.3,5000
14,Gore Verbinski,450.0,89.0,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.0,2013.0,6.5,48000
15,Zack Snyder,733.0,291.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225.0,2013.0,7.2,118000
16,Andrew Adamson,258.0,141.0,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225.0,2008.0,6.6,0
17,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000
18,Rob Marshall,448.0,241.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250.0,2011.0,6.7,58000
19,Barry Sonnenfeld,451.0,179.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225.0,2012.0,6.8,40000
20,Peter Jackson,422.0,255.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250.0,2014.0,7.5,65000
21,Marc Webb,599.0,262.0,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230.0,2012.0,7.0,56000
22,Ridley Scott,343.0,105.0,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200.0,2010.0,6.7,17000
23,Peter Jackson,509.0,258.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.0,2013.0,7.9,83000
24,Chris Weitz,251.0,70.0,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180.0,2007.0,6.1,0
25,Peter Jackson,446.0,218.0,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207.0,2005.0,7.2,0
26,James Cameron,315.0,658.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000
27,Anthony Russo,516.0,407.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250.0,2016.0,8.2,72000
28,Peter Berg,377.0,65.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.0,2012.0,5.9,44000
29,Colin Trevorrow,644.0,652.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000
30,Sam Mendes,750.0,304.0,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,1498.0,English,200.0,2012.0,7.8,80000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959,Robert Townsend,21.0,5.0,Comedy,Robert Townsend,Hollywood Shuffle,2770,32.0,English,0.0,1987.0,7.0,471
4962,Larry Blamire,88.0,0.0,Comedy|Horror|Sci-Fi,Fay Masterson,The Lost Skeleton of Cadavra,4117,118.0,English,0.0,2001.0,7.0,0
4964,E.L. Katz,193.0,0.0,Comedy|Crime|Drama|Horror|Thriller,Brighton Sharbino,Cheap Thrills,12796,52.0,English,0.0,2013.0,6.8,0
4971,Dennis Iliadis,241.0,32.0,Crime|Horror|Thriller,Tony Goldwyn,The Last House on the Left,67824,279.0,English,15.0,2009.0,6.6,0
4973,Darren Aronofsky,138.0,3.0,Drama|Mystery|Thriller,Mark Margolis,Pi,142619,586.0,English,0.0,1998.0,7.5,24000
4975,Myles Berkowitz,32.0,0.0,Biography|Comedy|Romance,Tia Carrere,20 Dates,1622,83.0,English,0.0,1998.0,5.3,30
4977,Morgan Spurlock,193.0,11.0,Comedy|Documentary|Drama,Chemeeka Walker,Super Size Me,85028,404.0,English,0.0,2004.0,7.3,0
4978,Brandon Trost,66.0,0.0,Comedy,Clifton Collins Jr.,The FP,1389,22.0,English,0.0,2011.0,5.6,0
4979,Joe Swanberg,65.0,0.0,Comedy|Drama,Anna Kendrick,Happy Christmas,5507,23.0,English,0.0,2014.0,5.6,812
4984,Edward Burns,36.0,10.0,Comedy|Drama|Romance,Shari Albert,The Brothers McMullen,6375,36.0,English,0.0,1995.0,6.6,265
4987,Lena Dunham,113.0,0.0,Comedy|Drama|Romance,Lena Dunham,Tiny Furniture,11816,35.0,English,0.0,2010.0,6.3,0
4997,David Gordon Green,75.0,0.0,Drama,Paul Schneider,George Washington,6246,76.0,English,0.0,2000.0,7.5,451
4998,Kevin Jordan,21.0,0.0,Comedy|Romance,Derick Martini,Smiling Fish & Goat on Fire,2631,26.0,English,0.0,1999.0,7.6,0
5004,Mike Bruce,3.0,0.0,Western,Joseph Campanella,The Legend of God's Gun,143,9.0,English,0.0,2007.0,4.1,13
5008,Kevin Smith,136.0,3.0,Comedy,Jason Mewes,Clerks,181749,615.0,English,0.0,1994.0,7.8,0
5009,James Bidgood,8.0,0.0,Drama|Fantasy,Don Brooks,Pink Narcissus,803,16.0,English,0.0,1971.0,6.7,85
5011,Neil LaBute,80.0,2.0,Comedy|Drama,Stacy Edwards,In the Company of Men,11550,197.0,English,0.0,1997.0,7.3,489
5012,David Ayer,233.0,10.0,Action|Crime|Drama|Thriller,Mireille Enos,Sabotage,47502,212.0,English,35.0,2014.0,5.7,10000
5015,Richard Linklater,61.0,1.0,Comedy|Drama,Tommy Pallotta,Slacker,15103,80.0,English,0.0,1991.0,7.1,2000
5021,Jay Duplass,51.0,0.0,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,71.0,English,0.0,2005.0,6.6,297
5023,Daryl Wein,22.0,0.0,Romance,Zoe Lister-Jones,Breaking Upwards,1194,8.0,English,0.0,2009.0,6.2,324
5025,John Waters,73.0,0.0,Comedy|Crime|Horror,Divine,Pink Flamingos,16792,183.0,English,0.0,1972.0,6.1,0
5026,Olivier Assayas,81.0,0.0,Drama|Music|Romance,Maggie Cheung,Clean,3924,39.0,French,0.0,2004.0,6.9,171
5027,Jafar Panahi,64.0,0.0,Drama,Fereshteh Sadre Orafaiy,The Circle,4555,26.0,Persian,0.0,2000.0,7.5,697
5029,Kiyoshi Kurosawa,78.0,0.0,Crime|Horror|Mystery|Thriller,KÃ´ji Yakusho,The Cure,6318,50.0,Japanese,1.0,1997.0,7.4,817
5033,Shane Carruth,143.0,0.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0,1992.0,6.9,0
5037,Edward Burns,14.0,0.0,Comedy|Drama,Kerry BishÃ©,Newlyweds,1338,14.0,English,0.0,2011.0,6.4,413
5042,Jon Gunn,43.0,0.0,Documentary,John August,My Date with Drew,4285,84.0,English,0.0,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [17]:
# Write your code for creating the profit column here
df6=df5.copy()
df6["Profit"]=df6["gross"]-df6["budget"]
df6

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.0
1,Gore Verbinski,302.0,309.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.0
2,Sam Mendes,602.0,200.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-45.0
3,Christopher Nolan,813.0,448.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.0
5,Andrew Stanton,462.0,73.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.0,2012.0,6.6,24000,-190.0
6,Sam Raimi,392.0,336.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258.0,2007.0,6.2,0,78.0
7,Nathan Greno,324.0,200.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260.0,2010.0,7.8,29000,-60.0
8,Joss Whedon,635.0,458.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250.0,2015.0,7.5,118000,208.0
9,David Yates,375.0,301.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250.0,2009.0,7.5,10000,51.0
10,Zack Snyder,673.0,330.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250.0,2016.0,6.9,197000,80.0
11,Bryan Singer,434.0,200.0,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209.0,2006.0,6.1,0,-9.0
12,Marc Forster,403.0,168.0,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200.0,2008.0,6.7,0,-32.0
13,Gore Verbinski,313.0,423.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225.0,2006.0,7.3,5000,198.0
14,Gore Verbinski,450.0,89.0,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.0,2013.0,6.5,48000,-126.0
15,Zack Snyder,733.0,291.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225.0,2013.0,7.2,118000,66.0
16,Andrew Adamson,258.0,141.0,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225.0,2008.0,6.6,0,-84.0
17,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.0
18,Rob Marshall,448.0,241.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250.0,2011.0,6.7,58000,-9.0
19,Barry Sonnenfeld,451.0,179.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225.0,2012.0,6.8,40000,-46.0
20,Peter Jackson,422.0,255.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250.0,2014.0,7.5,65000,5.0
21,Marc Webb,599.0,262.0,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230.0,2012.0,7.0,56000,32.0
22,Ridley Scott,343.0,105.0,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200.0,2010.0,6.7,17000,-95.0
23,Peter Jackson,509.0,258.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.0,2013.0,7.9,83000,33.0
24,Chris Weitz,251.0,70.0,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180.0,2007.0,6.1,0,-110.0
25,Peter Jackson,446.0,218.0,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207.0,2005.0,7.2,0,11.0
26,James Cameron,315.0,658.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.0
27,Anthony Russo,516.0,407.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250.0,2016.0,8.2,72000,157.0
28,Peter Berg,377.0,65.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.0,2012.0,5.9,44000,-144.0
29,Colin Trevorrow,644.0,652.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.0
30,Sam Mendes,750.0,304.0,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,1498.0,English,200.0,2012.0,7.8,80000,104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959,Robert Townsend,21.0,5.0,Comedy,Robert Townsend,Hollywood Shuffle,2770,32.0,English,0.0,1987.0,7.0,471,5.0
4962,Larry Blamire,88.0,0.0,Comedy|Horror|Sci-Fi,Fay Masterson,The Lost Skeleton of Cadavra,4117,118.0,English,0.0,2001.0,7.0,0,0.0
4964,E.L. Katz,193.0,0.0,Comedy|Crime|Drama|Horror|Thriller,Brighton Sharbino,Cheap Thrills,12796,52.0,English,0.0,2013.0,6.8,0,0.0
4971,Dennis Iliadis,241.0,32.0,Crime|Horror|Thriller,Tony Goldwyn,The Last House on the Left,67824,279.0,English,15.0,2009.0,6.6,0,17.0
4973,Darren Aronofsky,138.0,3.0,Drama|Mystery|Thriller,Mark Margolis,Pi,142619,586.0,English,0.0,1998.0,7.5,24000,3.0
4975,Myles Berkowitz,32.0,0.0,Biography|Comedy|Romance,Tia Carrere,20 Dates,1622,83.0,English,0.0,1998.0,5.3,30,0.0
4977,Morgan Spurlock,193.0,11.0,Comedy|Documentary|Drama,Chemeeka Walker,Super Size Me,85028,404.0,English,0.0,2004.0,7.3,0,11.0
4978,Brandon Trost,66.0,0.0,Comedy,Clifton Collins Jr.,The FP,1389,22.0,English,0.0,2011.0,5.6,0,0.0
4979,Joe Swanberg,65.0,0.0,Comedy|Drama,Anna Kendrick,Happy Christmas,5507,23.0,English,0.0,2014.0,5.6,812,0.0
4984,Edward Burns,36.0,10.0,Comedy|Drama|Romance,Shari Albert,The Brothers McMullen,6375,36.0,English,0.0,1995.0,6.6,265,10.0
4987,Lena Dunham,113.0,0.0,Comedy|Drama|Romance,Lena Dunham,Tiny Furniture,11816,35.0,English,0.0,2010.0,6.3,0,0.0
4997,David Gordon Green,75.0,0.0,Drama,Paul Schneider,George Washington,6246,76.0,English,0.0,2000.0,7.5,451,0.0
4998,Kevin Jordan,21.0,0.0,Comedy|Romance,Derick Martini,Smiling Fish & Goat on Fire,2631,26.0,English,0.0,1999.0,7.6,0,0.0
5004,Mike Bruce,3.0,0.0,Western,Joseph Campanella,The Legend of God's Gun,143,9.0,English,0.0,2007.0,4.1,13,0.0
5008,Kevin Smith,136.0,3.0,Comedy,Jason Mewes,Clerks,181749,615.0,English,0.0,1994.0,7.8,0,3.0
5009,James Bidgood,8.0,0.0,Drama|Fantasy,Don Brooks,Pink Narcissus,803,16.0,English,0.0,1971.0,6.7,85,0.0
5011,Neil LaBute,80.0,2.0,Comedy|Drama,Stacy Edwards,In the Company of Men,11550,197.0,English,0.0,1997.0,7.3,489,2.0
5012,David Ayer,233.0,10.0,Action|Crime|Drama|Thriller,Mireille Enos,Sabotage,47502,212.0,English,35.0,2014.0,5.7,10000,-25.0
5015,Richard Linklater,61.0,1.0,Comedy|Drama,Tommy Pallotta,Slacker,15103,80.0,English,0.0,1991.0,7.1,2000,1.0
5021,Jay Duplass,51.0,0.0,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,71.0,English,0.0,2005.0,6.6,297,0.0
5023,Daryl Wein,22.0,0.0,Romance,Zoe Lister-Jones,Breaking Upwards,1194,8.0,English,0.0,2009.0,6.2,324,0.0
5025,John Waters,73.0,0.0,Comedy|Crime|Horror,Divine,Pink Flamingos,16792,183.0,English,0.0,1972.0,6.1,0,0.0
5026,Olivier Assayas,81.0,0.0,Drama|Music|Romance,Maggie Cheung,Clean,3924,39.0,French,0.0,2004.0,6.9,171,0.0
5027,Jafar Panahi,64.0,0.0,Drama,Fereshteh Sadre Orafaiy,The Circle,4555,26.0,Persian,0.0,2000.0,7.5,697,0.0
5029,Kiyoshi Kurosawa,78.0,0.0,Crime|Horror|Mystery|Thriller,KÃ´ji Yakusho,The Cure,6318,50.0,Japanese,1.0,1997.0,7.4,817,-1.0
5033,Shane Carruth,143.0,0.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0,2004.0,7.0,19000,0.0
5034,Neill Dela Llana,35.0,0.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0,2005.0,6.3,74,0.0
5035,Robert Rodriguez,56.0,2.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0,1992.0,6.9,0,2.0
5037,Edward Burns,14.0,0.0,Comedy|Drama,Kerry BishÃ©,Newlyweds,1338,14.0,English,0.0,2011.0,6.4,413,0.0
5042,Jon Gunn,43.0,0.0,Documentary,John August,My Date with Drew,4285,84.0,English,0.0,2004.0,6.6,456,0.0

In [18]:
# Write your code for sorting the dataframe here
df7=df6.sort_values(by = ["Profit"],ascending = False)
df7

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.0
29,Colin Trevorrow,644.0,652.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.0
26,James Cameron,315.0,658.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.0
3024,George Lucas,282.0,460.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.0
3080,Steven Spielberg,215.0,434.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.0,1982.0,7.9,34000,424.0
794,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.0
17,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.0
509,Roger Allers,186.0,422.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.0
240,George Lucas,320.0,474.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.0
66,Christopher Nolan,645.0,533.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.0
439,Gary Ross,673.0,407.0,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.0
812,Tim Miller,579.0,363.0,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.0,2016.0,8.1,117000,305.0
186,Francis Lawrence,502.0,424.0,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.0,2013.0,7.6,82000,294.0
697,Steven Spielberg,308.0,356.0,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.0,1993.0,8.1,19000,293.0
814,Clint Eastwood,490.0,350.0,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.0,2014.0,7.3,112000,292.0
521,Pierre Coffin,306.0,368.0,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.0,2013.0,7.5,56000,292.0
582,Andrew Adamson,205.0,436.0,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.0,2004.0,7.2,0,286.0
338,Andrew Stanton,301.0,380.0,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.0,2003.0,8.2,11000,286.0
339,Peter Jackson,328.0,377.0,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.0,2003.0,8.9,16000,283.0
1536,Richard Marquand,197.0,309.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.0,1983.0,8.4,14000,277.0
836,Robert Zemeckis,149.0,329.0,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.0,1994.0,8.8,59000,274.0
2051,Irvin Kershner,223.0,290.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.0,1980.0,8.8,17000,272.0
236,George Lucas,359.0,380.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.0,2005.0,7.6,10000,267.0
2601,Chris Columbus,102.0,285.0,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.0,1990.0,7.5,20000,267.0
161,Sam Raimi,291.0,403.0,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.0,2002.0,7.3,5000,264.0
563,Kyle Balda,308.0,336.0,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.0,2015.0,6.4,70000,262.0
1181,M. Night Shyamalan,234.0,293.0,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.0,1999.0,8.1,14000,253.0
2917,Steven Spielberg,385.0,260.0,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.0,1975.0,8.0,21000,252.0
125,Chris Buck,406.0,400.0,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.0,2013.0,7.6,58000,250.0
519,Yarrow Cheney,165.0,323.0,Animation|Comedy|Family,Steve Coogan,The Secret Life of Pets,24407,155.0,English,75.0,2016.0,6.8,36000,248.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3879,Joe Wright,256.0,34.0,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.0,2015.0,5.8,24000,-116.0
145,Joe Wright,256.0,34.0,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.0,2015.0,5.8,24000,-116.0
303,Joe Wright,256.0,34.0,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.0,2015.0,5.8,24000,-116.0
113,Oliver Stone,248.0,34.0,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.0,2004.0,5.5,0,-121.0
14,Gore Verbinski,450.0,89.0,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.0,2013.0,6.5,48000,-126.0
143,Simon Wells,132.0,21.0,Action|Adventure|Animation|Comedy|Family|Sci-Fi,Elisabeth Harnois,Mars Needs Moms,17590,112.0,English,150.0,2011.0,5.4,0,-129.0
62,Lana Wachowski,384.0,47.0,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.0,2015.0,5.4,44000,-129.0
49,Bryan Singer,338.0,65.0,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.0,2013.0,6.3,22000,-130.0
85,Carl Rinsch,218.0,38.0,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.0,2013.0,6.3,35000,-137.0
2339,Jean-Marie PoirÃ©,8.0,0.0,Comedy|Family|Fantasy|Sci-Fi,Christian Clavier,Les couloirs du temps: Les visiteurs II,7147,16.0,French,140.0,1998.0,6.0,136,-140.0
28,Peter Berg,377.0,65.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.0,2012.0,5.9,44000,-144.0
3877,R. Balki,12.0,0.0,Comedy|Drama,Vidya Balan,Paa,7295,49.0,Hindi,150.0,2009.0,7.2,504,-150.0
1782,Jacques Perrin,100.0,10.0,Documentary,Jacques Perrin,Winged Migration,10369,153.0,English,160.0,2001.0,8.0,1000,-150.0
91,Robert Zemeckis,188.0,0.0,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.0,2004.0,6.6,10000,-165.0
3659,Prachya Pinkaew,112.0,11.0,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,Thai,200.0,2005.0,7.1,0,-189.0
5,Andrew Stanton,462.0,73.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.0,2012.0,6.6,24000,-190.0
2740,Tony Jaa,110.0,0.0,Action,Nirut Sirichanya,Ong-bak 2,24570,72.0,Thai,300.0,2008.0,6.2,0,-300.0
1016,Luc Besson,111.0,14.0,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.0,1999.0,6.4,0,-376.0
3311,Chatrichalerm Yukol,31.0,0.0,Action|Adventure|Drama|History|War,Sarunyu Wongkrachang,The Legend of Suriyothai,1666,47.0,Thai,400.0,2001.0,6.6,124,-400.0
1338,John Woo,160.0,0.0,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,Mandarin,553.0,2008.0,7.4,0,-553.0
3273,Anurag Basu,41.0,1.0,Action|Drama|Romance|Thriller,BÃ¡rbara Mori,Kites,9673,106.0,English,600.0,2010.0,6.0,0,-599.0
3075,Karan Johar,20.0,3.0,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,264.0,Hindi,700.0,2006.0,6.0,659,-697.0
3851,Carlos Saura,35.0,1.0,Drama|Musical,MÃ­a Maestro,Tango,2412,40.0,Spanish,700.0,1998.0,7.2,539,-699.0
4542,Takao Okawara,107.0,10.0,Action|Adventure|Drama|Sci-Fi|Thriller,Hiroshi Abe,Godzilla 2000,5442,140.0,Japanese,1000.0,1999.0,6.0,339,-990.0
3423,Katsuhiro Ã”tomo,150.0,0.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.0,1988.0,8.1,0,-1100.0
2334,Katsuhiro Ã”tomo,105.0,0.0,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.0,2004.0,6.9,973,-2127.0
2323,Hayao Miyazaki,174.0,2.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.0,1997.0,8.4,11000,-2398.0
3005,Lajos Koltai,73.0,0.0,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.0,2005.0,7.1,607,-2500.0
3859,Chan-wook Park,202.0,0.0,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.0,2005.0,7.7,4000,-4200.0
2988,Joon-ho Bong,363.0,2.0,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.0,2006.0,7.0,7000,-12213.0

In [19]:
#top10 = # Write your code to get the top 10 profiting movies here
top10=df7.head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.0
29,Colin Trevorrow,644.0,652.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.0
26,James Cameron,315.0,658.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.0
3024,George Lucas,282.0,460.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.0
3080,Steven Spielberg,215.0,434.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.0,1982.0,7.9,34000,424.0
794,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.0
17,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.0
509,Roger Allers,186.0,422.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.0
240,George Lucas,320.0,474.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.0
66,Christopher Nolan,645.0,533.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.0

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [34]:
# Write your code for dropping duplicate values here
df8=df7.drop_duplicates()
df8.shape
#df8.sort_values(by = ["Profit"], ascending = False)

(3856, 14)

In [53]:
# Write code for repeating subtask 2 here
df9=df8.copy()
df9["Profit"]=df9["gross"] - df9["budget"]
#df9[df9["Profit1"]-df9["Profit"]  > 0 ]
df10=df9.sort_values(by = ["Profit"],ascending = False)
df10=df9.head(10)
df10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.0
29,Colin Trevorrow,644.0,652.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.0
26,James Cameron,315.0,658.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.0
3024,George Lucas,282.0,460.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.0
3080,Steven Spielberg,215.0,434.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.0,1982.0,7.9,34000,424.0
794,Joss Whedon,703.0,623.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.0
509,Roger Allers,186.0,422.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.0
240,George Lucas,320.0,474.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.0
66,Christopher Nolan,645.0,533.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.0
439,Gary Ross,673.0,407.0,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.0

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [101]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'

import numpy as np
#IMDb_Top_250 = df9.loc[df9["num_voted_users"]>250]
df9.columns
IMDb_Top_250=df9.loc[df9["num_voted_users"]>25000].sort_values(by = ["imdb_score"], ascending = False).head(250)
IMDb_Top_250["rank"]=np.arange(1,251)
#x=np.arange(1,251)
#df10
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,rank
3344,Karan Johar,210.0,4.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.0,2010.0,8.0,27000,-8.0,201
3510,Yash Chopra,29.0,2.0,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.0,2004.0,7.9,2000,-5.0,246

In [102]:
#Top_Foreign_Lang_Film = # Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDb_Top_250.loc[IMDb_Top_250["language"] != 'English']
Top_Foreign_Lang_Film.loc[Top_Foreign_Lang_Film["language"] == 'Hindi']
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,rank
4498,Sergio Leone,181.0,6.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.0,1966.0,8.9,20000,5.0,7
4747,Akira Kurosawa,153.0,0.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.0,1954.0,8.7,11000,-2.0,17
4029,Fernando Meirelles,214.0,7.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.0,2002.0,8.7,28000,4.0,19
2373,Hayao Miyazaki,246.0,10.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.0,2001.0,8.6,28000,-9.0,24
4259,Florian Henckel von Donnersmarck,215.0,11.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.0,2006.0,8.5,39000,9.0,30
4921,Majid Majidi,46.0,0.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.0,1997.0,8.5,0,0.0,40
2970,Wolfgang Petersen,96.0,11.0,Adventure|Drama|Thriller|War,JÃ¼rgen Prochnow,Das Boot,168203,426.0,German,14.0,1981.0,8.4,11000,-3.0,49
2323,Hayao Miyazaki,174.0,2.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.0,1997.0,8.4,11000,-2398.0,50
4659,Asghar Farhadi,354.0,7.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.0,2011.0,8.4,48000,7.0,57
1329,S.S. Rajamouli,44.0,6.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.0,2015.0,8.4,21000,-12.0,58
4105,Chan-wook Park,305.0,2.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.0,2003.0,8.4,43000,-1.0,60
1298,Jean-Pierre Jeunet,242.0,33.0,Comedy|Romance,Mathieu Kassovitz,AmÃ©lie,534262,1314.0,French,77.0,2001.0,8.4,39000,-44.0,61
2829,Oliver Hirschbiegel,192.0,5.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.0,2004.0,8.3,14000,-8.0,69
2734,Fritz Lang,260.0,0.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.0,1927.0,8.3,12000,-6.0,72
4033,Thomas Vinterberg,349.0,0.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.0,2012.0,8.3,60000,-3.0,81
4000,Juan JosÃ© Campanella,262.0,20.0,Drama|Mystery|Thriller,Ricardo DarÃ­n,The Secret in Their Eyes,131831,231.0,Spanish,2.0,2009.0,8.2,33000,18.0,89
3550,Denis Villeneuve,226.0,6.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.0,2010.0,8.2,37000,0.0,95
2551,Guillermo del Toro,406.0,37.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.0,2006.0,8.2,27000,24.0,97
2047,Hayao Miyazaki,212.0,4.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.0,2004.0,8.2,13000,-20.0,103
3553,JosÃ© Padilha,142.0,0.0,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.0,2007.0,8.1,11000,-4.0,108
4461,Thomas Vinterberg,98.0,1.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.0,1998.0,8.1,5000,0.0,131
3423,Katsuhiro Ã”tomo,150.0,0.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.0,1988.0,8.1,0,-1100.0,133
2914,Je-kyu Kang,86.0,1.0,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.0,2004.0,8.1,0,-11.0,139
2830,Alejandro AmenÃ¡bar,157.0,2.0,Biography|Drama|Romance,BelÃ©n Rueda,The Sea Inside,64556,140.0,Spanish,10.0,2004.0,8.1,0,-8.0,143
4267,Alejandro G. IÃ±Ã¡rritu,157.0,5.0,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.0,2000.0,8.1,11000,3.0,149
4284,Ari Folman,231.0,2.0,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.0,2008.0,8.0,0,1.0,153
4144,Walter Salles,71.0,5.0,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.0,1998.0,8.0,0,3.0,184
4897,Sergio Leone,122.0,3.0,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.0,1964.0,8.0,0,3.0,190
3344,Karan Johar,210.0,4.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.0,2010.0,8.0,27000,-8.0,201
3456,Vincent Paronnaud,242.0,4.0,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.0,2007.0,8.0,14000,-3.0,204
4640,Cristian Mungiu,233.0,1.0,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.0,2007.0,7.9,14000,1.0,206
1171,Yimou Zhang,283.0,0.0,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.0,2002.0,7.9,0,-31.0,230
2605,Ang Lee,287.0,128.0,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.0,2000.0,7.9,0,113.0,242
3510,Yash Chopra,29.0,2.0,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.0,2004.0,7.9,2000,-5.0,246
4415,FabiÃ¡n Bielinsky,94.0,1.0,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125.0,Spanish,1.0,2000.0,7.9,0,0.0,247
3264,Michael Haneke,447.0,0.0,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.0,2012.0,7.9,33000,-8.0,248

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [125]:
# Write your code for extracting the top 10 directors here
dir_name=df9.groupby('director_name')
top10director=dir_name["imdb_score"].mean().sort_values(ascending = False).head(10)
list(top10director.index)

['Charles Chaplin',
 'Tony Kaye',
 'Ron Fricke',
 'Damien Chazelle',
 'Majid Majidi',
 'Alfred Hitchcock',
 'Sergio Leone',
 'Christopher Nolan',
 'Asghar Farhadi',
 'Richard Marquand']

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [218]:
# Write your code for extracting the first two genres of each movie here
#for i in range(df9.shape[1]):
    #df9["genre_1"]=df9["genres"].str.split('|')[i][0]
    #df9["genre_2"]=df9["genres"].str.split('|')[i][1] 
######## Why For loop is not working ##########
df9["genre_1"]=df9["genres"].str.split('|').apply(lambda x: x[0])
df9["genre_2"]=df9["genres"].str.split('|').apply(lambda x: x[1] if len(x) > 1 else x[0])
df10 = df9.groupby(["genre_1","genre_2"])
PopGenre=df10["gross"].mean().sort_values(ascending = False).head(5)
PopGenre

genre_1    genre_2
Family     Sci-Fi       434.000000
Adventure  Sci-Fi       228.000000
           Family       118.411765
           Animation    116.547009
Action     Adventure    109.182039
Name: gross, dtype: float64

In [205]:
df9["genres"].str.split('|')[3]

['Action', 'Thriller']

In [ ]:
movies_by_segment = # Write your code for grouping the dataframe here

In [ ]:
PopGenre = # Write your code for getting the 5 most popular combo of genres here

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [281]:
# Write your code for creating three new dataframes here

#Meryl_Streep = # Include all movies in which Meryl_Streep is the lead
Meryl_Streep=df9.loc[df9["actor_1_name"] == 'Meryl Streep' ]
Meryl_Streep.shape

(11, 16)

In [280]:
#Leo_Caprio = # Include all movies in which Leo_Caprio is the lead
#Leo_Caprio = df9.loc[df9["actor_1_name"].str.contains('Leo')]
#Leo_Caprio
df_not_null=df9.loc[~df9["actor_1_name"].isnull()]
Leo_Caprio = df_not_null.loc[df_not_null["actor_1_name"].str.contains('Leo.*Cap')]
Leo_Caprio.shape

(21, 16)

In [279]:
#Brad_Pitt = # Include all movies in which Brad_Pitt is the lead
Brad_Pitt = df9.loc[df9["actor_1_name"] == 'Brad Pitt']
Brad_Pitt.shape

(17, 16)

In [307]:
# Write your code for combining the three dataframes here
combined=pd.concat([Leo_Caprio,Meryl_Streep,Brad_Pitt],axis=0)
combined.shape

comb=Leo_Caprio.append(Meryl_Streep.append(Brad_Pitt))
comb.columns

Index(['director_name', 'num_critic_for_reviews', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'num_user_for_reviews', 'language', 'budget', 'title_year',
       'imdb_score', 'movie_facebook_likes', 'Profit', 'genre_1', 'genre_2'],
      dtype='object')

In [290]:
# Write your code for grouping the combined dataframe here
com_gr=combined.groupby(["actor_1_name"])

In [315]:
# Write the code for finding the mean of critic reviews and audience reviews here
x=com_gr["num_critic_for_reviews","num_user_for_reviews"].mean().sort_values(by =["num_critic_for_reviews","num_user_for_reviews"],ascending = False)
x

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476            914.476190
Brad Pitt                      245.000000            742.352941
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!